application: data-well
version: v1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: client/dist/static

- url: /jsapi.*
  script: _go_app

#- url: /api.*
#  script: _go_app

- url: /.*
  static_files: client/dist/index.html
  upload: client/dist/index.html

skip_files:
- ^client(?!/dist)/.*$
- ^keys-sample.json$
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
