application: data-well
version: v1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  script: _go_app
  login: admin

- url: /.*/.*
  script: _go_app
  login: required

- url: /.*
  script: _go_app
