application: data-well
version: v1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static

- url: /api/.*
  script: _go_app
  login: required
  auth_fail_action: unauthorized

- url: /.*
  script: _go_app

# ignore the client source dir, when present, with skip_files
